<?php
$active_group = 'default';
$active_record = TRUE;
$db['default']['username'] = 'root';
$db['default']['password'] = '9uO9hWoYj#Lz';
$db['default']['hostname'] = 'localhost';
$db['default']['database'] = 'OpenVBX';
$db['default']['dbdriver'] = 'mysqli';
$db['default']['dbprefix'] = '';
$db['default']['pconnect'] = FALSE;
$db['default']['db_debug'] = FALSE;
$db['default']['cache_on'] = FALSE;
$db['default']['cachedir'] = '';
$db['default']['char_set'] = 'utf8';
$db['default']['dbcollat'] = 'utf8_general_ci';
/* Autogenerated Configuration for db 2014-07-25 */
